### ISSUE TITLE
How does auth work with HTTP and private functions?

### ISSUE THREAD

**Issue by clayne11** [poly/f#4]
If you call a private function over HTTPS, how do you authenticate it?

Also, is there a reason you can't use POST requests and have a body which would allow for numbers as well as strings since all URL params are made into strings.

**Comment by keithwhor** [comment]
We'll be doing Auth via the HTTP Authorization header as part of the `f` package.

You can use POST requests using `x-www-form-urlencoded` values, which are converted to strings, or by using `application/json` which retain their initial types.

For POST there are two options; send as a plain object with any keys which is converted into `params.kwargs`, or send as an object with two keys specifically: `{args: [], kwargs: {}}`. Note that `args` *must* be an `Array` and `kwargs` *must* be an `Object`.

The latter is the default method used when calling

```javascript
f('user/service')(arg0, arg1, {kwarg: 'x'}, (err, result) => { /* */ });
```

**Comment by clayne11** [comment]
Am I missing something in the docs? I'd like to be able to call my function from a webhook. I don't see anything about POST or HTTP authentication in the docs.

**Comment by keithwhor** [comment]
You'll have to roll your own auth using `params.kwargs` presently. We'll be adding in authentication keys shortly to auth other Polybit users easily.
